name: ML CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python train.py
      - name: Test model
        run: python test_model.py
      - name: Build Docker image
        run: docker build -t ml-cicd-demo:latest .
      # - name: Push Docker image to Docker Hub
      #   run: |
      #     echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #     docker tag ml-cicd-demo:latest ${{ secrets.DOCKERHUB_USERNAME }}/ml-cicd-demo:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-cicd-demo:latest

